[project]
authors = ["Muhammad Jarir Kanji <mjkanji@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dbt_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
duckdb-cli = ">=1.0.0,<2"

[pypi-dependencies]
dagster = ">=1.8.4, <2"
dagster-cloud = ">=1.8.4, <2"
dagster-dbt = ">=0.24.4, <0.25"
dbt-core = ">=1.8.6, <2"
dbt-duckdb = ">=1.8.3, <2"
duckdb = ">=1.0.0, <2"
ruff = ">=0.6.3, <0.7"
sqlfluff = ">=3.1.1, <4"
dbt-coves = ">=1.8.6, <2"
dagster-webserver = ">=1.8.4, <2"
quick-deliver-pipeline = { path = "./", editable = true}
sqlfluff-templater-dbt = ">=3.1.1, <4"
