name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}/.github/workflows/
  DBT_PROJECT_DIR: ${{ github.workspace }}/dbt_project/

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: setup-pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        cache: true
    - name: Set up and populate DuckDB 
      working-directory: ./dbt_project
      run: |
        pixi run duckdb mydb.ddb < analyses/ddl.sql
        pixi run duckdb mydb.ddb < analyses/dummy_data.sql
        pixi run duckdb mydb.ddb 'show all tables'
        pixi run duckdb mydb.ddb 'select * from raw_couriers'

    - name: Run DBT
      working-directory: ./dbt_project
      run: |
        pixi run dbt deps
        pixi run dbt run
        pixi run dbt docs generate
    - name: Print catalog
      run: |
        echo "TARGET DIR ----------------"
        ls dbt_project/target/
        echo "CATALOG FILE -------------"
        cat dbt_project/target/catalog.json
        echo "DONE -----------"
    - uses: pre-commit/action@v3.0.1
      # with:
      #   extra_args: dbt-docs-generate --all-files
    - name: Print things
      run: |
        ls .
        ls dbt_project/
        ls dbt_project/target/
        cat dbt_project/target/catalog.json
